const sharp = require('sharp');
const ImageLog = require('../models/ImageLog');

/**
 * Smart inpainting: fills a region by sampling the surrounding border pixels
 * and creating a smooth gradient fill — no blur artifacts, color stays natural.
 */
async function inpaintRegion(inputBuffer, left, top, width, height) {
    const metadata = await sharp(inputBuffer).metadata();
    const imgW = metadata.width;
    const imgH = metadata.height;

    // Clamp to image boundaries
    const safeLeft   = Math.max(0, left);
    const safeTop    = Math.max(0, top);
    const safeRight  = Math.min(imgW, left + width);
    const safeBottom = Math.min(imgH, top + height);
    const safeW = safeRight - safeLeft;
    const safeH = safeBottom - safeTop;

    if (safeW <= 0 || safeH <= 0) return inputBuffer;

    // Sample border pixels (above, left, right edge rows/columns near the region)
    const sampleSize = Math.max(4, Math.floor(Math.min(safeW, safeH) * 0.15));

    // Sample patch ABOVE the watermark region
    const sampleTop  = Math.max(0, safeTop - sampleSize);
    const sampleH    = Math.min(sampleSize, safeTop);

    let fillR = 128, fillG = 128, fillB = 128;

    if (sampleH > 0) {
        // Get raw pixel data from the sample strip above
        const { data } = await sharp(inputBuffer)
            .extract({ left: safeLeft, top: sampleTop, width: safeW, height: sampleH })
            .ensureAlpha()
            .raw()
            .toBuffer({ resolveWithObject: true });

        let r = 0, g = 0, b = 0, count = 0;
        for (let i = 0; i < data.length; i += 4) {
            r += data[i];
            g += data[i + 1];
            b += data[i + 2];
            count++;
        }
        if (count > 0) {
            fillR = Math.round(r / count);
            fillG = Math.round(g / count);
            fillB = Math.round(b / count);
        }
    } else {
        // Sample from below if at top edge
        const sampleBot = Math.min(imgH - 1, safeBottom + sampleSize);
        const sampleBH  = Math.min(sampleSize, imgH - safeBottom);
        if (sampleBH > 0) {
            const { data } = await sharp(inputBuffer)
                .extract({ left: safeLeft, top: safeBottom, width: safeW, height: sampleBH })
                .ensureAlpha()
                .raw()
                .toBuffer({ resolveWithObject: true });

            let r = 0, g = 0, b = 0, count = 0;
            for (let i = 0; i < data.length; i += 4) {
                r += data[i];
                g += data[i + 1];
                b += data[i + 2];
                count++;
            }
            if (count > 0) {
                fillR = Math.round(r / count);
                fillG = Math.round(g / count);
                fillB = Math.round(b / count);
            }
        }
    }

    // Create a solid color fill patch matching the sampled background color
    const fillPatch = await sharp({
        create: {
            width: safeW,
            height: safeH,
            channels: 3,
            background: { r: fillR, g: fillG, b: fillB }
        }
    }).png().toBuffer();

    // Composite the fill patch onto the original image
    return await sharp(inputBuffer)
        .composite([{ input: fillPatch, top: safeTop, left: safeLeft }])
        .toBuffer();
}

/**
 * ChatGPT / DALL-E watermark:
 *   – Very small text logo in the BOTTOM-RIGHT corner
 *   – Approx 5.5% width × 1.8% height of image
 */
async function removeChatGPTWatermark(inputBuffer, metadata) {
    const wmW = Math.ceil(metadata.width  * 0.065); // slightly wider margin
    const wmH = Math.ceil(metadata.height * 0.028); // slightly taller margin

    const left = metadata.width  - wmW;
    const top  = metadata.height - wmH;

    return await inpaintRegion(inputBuffer, left, top, wmW, wmH);
}

/**
 * Gemini watermark:
 *   – "Generated by Gemini" text at the BOTTOM-LEFT corner
 *   – Approx 20% width × 2.5% height of image
 */
async function removeGeminiWatermark(inputBuffer, metadata) {
    const wmW = Math.ceil(metadata.width  * 0.28); // wider for "Generated by Gemini" text
    const wmH = Math.ceil(metadata.height * 0.032);

    const left = 0;
    const top  = metadata.height - wmH;

    return await inpaintRegion(inputBuffer, left, top, wmW, wmH);
}

/**
 * Auto-detect: Try to detect which watermark is present.
 * Strategy: sample bottom-left and bottom-right pixel brightness.
 * A dark text watermark leaves detectable contrast vs background.
 * We apply both removals to be safe — removes both if present.
 */
async function removeAllWatermarks(inputBuffer, metadata) {
    let buf = inputBuffer;
    buf = await removeChatGPTWatermark(buf, metadata);
    const freshMeta = await sharp(buf).metadata(); // re-read after first pass
    buf = await removeGeminiWatermark(buf, freshMeta);
    return buf;
}

// ─────────────────────────────────────────────
// Controller
// ─────────────────────────────────────────────
const processImage = async (req, res) => {
    try {
        if (!req.file) {
            return res.status(400).json({ error: 'No image uploaded' });
        }

        const inputBuffer = req.file.buffer;
        const metadata    = await sharp(inputBuffer).metadata();

        // watermarkType: 'auto' | 'chatgpt' | 'gemini'  (sent from frontend)
        const wmType = (req.body.watermarkType || 'auto').toLowerCase();

        let processedBuffer;

        if (wmType === 'chatgpt') {
            const cleaned = await removeChatGPTWatermark(inputBuffer, metadata);
            processedBuffer = await sharp(cleaned)
                .withMetadata()
                .toFormat(metadata.format || 'png')
                .toBuffer();

        } else if (wmType === 'gemini') {
            const cleaned = await removeGeminiWatermark(inputBuffer, metadata);
            processedBuffer = await sharp(cleaned)
                .withMetadata()
                .toFormat(metadata.format || 'png')
                .toBuffer();

        } else {
            // Auto — remove both
            const cleaned = await removeAllWatermarks(inputBuffer, metadata);
            processedBuffer = await sharp(cleaned)
                .withMetadata()
                .toFormat(metadata.format || 'png')
                .toBuffer();
        }

        // Save log to MongoDB gracefully
        try {
            const newLog = new ImageLog({
                originalName: req.file.originalname,
                processedPath: 'in-memory'
            });
            await newLog.save();
        } catch (dbError) {
            console.log('Could not save to MongoDB, skipping log:', dbError.message);
        }

        const mimeType = `image/${metadata.format || 'png'}`;
        res.set('Content-Type', mimeType);
        res.set('Content-Disposition', `attachment; filename="watermark-removed-${req.file.originalname}"`);
        res.send(processedBuffer);

    } catch (error) {
        console.error('Error processing image:', error);
        res.status(500).json({ error: 'Failed to process image' });
    }
};

module.exports = { processImage };
